# Book settings
title: The pyOpenSci Developer Guide
author: The pyOpenSci Community
logo: images/logo/logo.png
exclude_patterns: ["README.md"]

repository:
  url: https://github.com/pyOpenSci/contributing-guide
  branch: main

parse:
  myst_enable_extensions:
    - sphinx_copybutton


html:
  favicon: images/logo/logo.png
  google_analytics_id: UA-141260825-1
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  announcement: "<div class='header__block'>ATTENTION
                <p>
                We are currently updating this book so please check back frequently! 
                The packaging guide is currently the most
                out of date section in this guidebook.
                </p>
                </div>
                "